# scribe_agent.py – Scroll Writer Agent (ScribeGPT)

import sys
from datetime import datetime

def write_scroll(scroll_name, title, summary):
    filename = f"{scroll_name}.md"
    with open(filename, "w") as f:
        f.write(f"# {title}\n\n")
        f.write(f"**Scroll ID:** {scroll_name}\n")
        f.write(f"**Author:** ScribeGPT\n")
        f.write(f"**Timestamp:** {datetime.now().isoformat()}\n\n")
        f.write(f"## Purpose\n{summary}\n")
        f.write(f"\n---\n\n> *Auto-generated by ScribeGPT agent.*\n")

    print(f"✅ Scroll '{filename}' created.")

    with open("glyph_log.txt", "a") as log:
        log.write(f"[{datetime.now().isoformat()}] Scroll generated: {scroll_name}\n")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python3 scribe_agent.py <scroll_id> <summary>")
    else:
        scroll_id = sys.argv[1]
        summary = " ".join(sys.argv[2:])
        write_scroll(scroll_id, f"Scroll – {scroll_id}", summary)

